name: Generation Jaguar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#006778'
    - '#ffffff'
    - '#9f792c'
    - '#69a6af'
  brandStrength: 0.34244976635091007
  lightness: 0.3116444363258779
  saturation: 0.7876044653821737
  rhythmicContrast: 0.4714766317047179
purpose: []
