name: Generation Jaguar
favicon: null
layout_spectrum: 0.6258757431060076
typography_spectrum: 0.5783372703008354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.34244976635091007
  lightness: 0.3116444363258779
  saturation: 0.7876044653821737
  rhythmicContrast: 0.4714766317047179
purpose: []
